show-sorting: show-sorting.cpp Plotter.cpp
	g++ -o show-sorting show-sorting.cpp Plotter.cpp -L. -lSDL

show-sorting2: show-sorting.cpp Plotter.cpp
	g++ -o show-sorting show-sorting.cpp Plotter.cpp -lSDL
